Refactoring GameObject
Bubbad/Bubba-3D pull request #81
Opened 2016-10-25 22:23 UTC by DunderRoffe

* Documentation for GameObject
* Handling all GameObject pointers as std::shared_ptr<GameObject>

2016-10-28 18:27 UTC, SiXoS requested changes

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Add a IRenderComponent to the GameObject.
Unecessary comment, will just be outdated if we change type name

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Add a component to the GameObject.
Unecessary comment

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Get the model matrix of the GameObject.
Unecessary comment

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Set the absoulte scale of the GameObject.
Isn't this relative to the parent?

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Get scale of the GameObject relative to default scale.
Original rotation might be better than default? Or model rotation or something

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Get the rotation of the GameObject relative to default rotation.
original?

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * given child GameObject. Requires that the child being added dose not
does*

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Get the minimal boundng sphere that contains the Mesh of the GameObject.
bounding

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Check if the GameObject is dirty or not.
Unecessary comment

2016-10-28 18:27 UTC, SiXoS commented on includes/GameObject.h
> +     * Get a AABB fitting the GameObjects Mesh.
an*

2016-10-28 20:23 UTC, Bubbad requested changes

2016-10-28 20:23 UTC, Bubbad commented on src/objects/GameObject.cpp
> -}
Why were these constructors removed?

2016-10-28 20:23 UTC, Bubbad commented on src/objects/GameObject.cpp
> +    }
Perhaps this method should be renamed? It does more than adding children. Something like connectChildAndSetThisAsParent? Long, but at least it's very descriptive

2016-11-06 21:17 UTC, DunderRoffe commented
Will have to rework this...
Somehow movement is not stopped by collision...

2016-11-28 18:31 UTC, closed without merging