Added GPU based wind
Bubbad/Bubba-3D pull request #95
Opened 2017-11-26 12:56 UTC by Bubbad

How an object is affected by wind is painted as vertex colors on the object as described in https://mtnphil.wordpress.com/2011/10/18/wind-animations-for-vegetation/ with the difference that the branch attenuation is inverted when coloring, not in shaders.

A scene now has a global wind. Objects are by default not affected by it, but can be if affectedByWind attribute is set on it. 
An object can be affected in three different ways; stem, branch and leaf bending (see article above), which are specified on the object itself. (It needs to be on the GameObject as the renderer sets this information)

2017-11-26 12:58 UTC, Bubbad commented on includes/IShader.h
> +    virtual void checkErrors(GLuint &shader) = 0;
Bonus: Fixed a bug where printing shader errors crashed before the message was printed

2017-11-26 13:00 UTC, Bubbad commented on shaders/simple.frag
> +    if(object_alpha < 0.1) {
Not sure why this appears as diff, it's rebased into the branch from master

2017-11-26 13:02 UTC, Bubbad commented on src/glutil/glutil.cpp
> -			assert(false);
This made it crash before printing errors

2017-11-26 13:03 UTC, Bubbad commented on src/objects/Mesh.cpp
> +        unsigned int j = 0;
Previously, we only loaded the first vertex color buffer, but there can be many!

2017-12-12 16:49 UTC, DunderRoffe requested changes

2017-12-12 16:49 UTC, DunderRoffe commented on src/core/Renderer.cpp
> +        drawModel(transparentObject, shaderProgram);
code duplication

2017-12-12 16:49 UTC, DunderRoffe commented on src/glutil/glutil.cpp
> +//			assert(false);
Remove code instead of commenting it out.

2017-12-12 16:49 UTC, DunderRoffe commented on src/objects/Mesh.cpp
> +            if (paiMesh->HasVertexColors(j)) {
The contents of this do loop should be extracted to a function for read ability

2018-05-09 19:38 UTC, DunderRoffe approved these changes

2018-05-09 19:38 UTC, merged